export {
  captureNoteRequestSchema,
  captureNoteResponseSchema,
  classificationSchema,
  deleteAccountRequestSchema,
  deleteAccountResponseSchema,
  managePracticeRequestSchema,
  managePracticeResponseSchema,
  searchNotesRequestSchema,
  searchNotesResponseSchema,
  type CaptureNoteRequest,
  type CaptureNoteResponse,
  type Classification,
  type DeleteAccountRequest,
  type DeleteAccountResponse,
  type ManagePracticeRequest,
  type ManagePracticeResponse,
  type PracticeEntry,
  type PracticeState,
  type SearchMatch,
  type SearchNotesRequest,
  type SearchNotesResponse,
} from '../../../packages/shared/src/contracts/index.ts';

export {
  MIN_SYNTHESIS_SIMILARITY,
  OPENAI_EMBEDDING_DIMENSIONS,
  OPENAI_EMBEDDING_MODEL,
  OPENAI_TEXT_MODEL,
} from '../../../packages/shared/src/constants/index.ts';
